#!/usr/bin/env bash
set -euo pipefail

cargo fmt --all
cargo clippy --workspace --all-targets --fix --allow-dirty >/dev/null 2>&1 || true
cargo clippy --workspace --all-targets
cargo nextest run --all --no-fail-fast
cargo llvm-cov-easy nextest +nightly --workspace --branch --fail-under-lines 100 --fail-under-regions 100 --fail-under-functions 100
cargo deny check
polydup scan . -t 75 -s 0.9 -q
